import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {freshState,localDate,nextDate,nextInterval,score,type State} from '@/lib/core';
import {lessons} from '@/lib/content';
import {z} from 'zod';
const input=z.object({action:z.enum(['profile','start','swap','attempt','advance','beat','saveExpression','review','deleteExpression','bookmark','candidate','reset']),session:z.string().optional(),key:z.string().optional(),answer:z.string().max(2000).optional(),captions:z.boolean().optional(),skip:z.boolean().optional(),index:z.number().int().min(0).max(100).optional(),success:z.boolean().optional(),profile:z.object({name:z.string().min(1).max(40),timezone:z.string().max(80),mode:z.union([z.literal(30),z.literal(60)]),interests:z.array(z.string().max(30)).max(5),onboarded:z.boolean()}).optional()});
function view(s:State){const {videos: privateVideos,netflixClips: privateNetflix,...publicState}=s;void privateVideos;void privateNetflix;return {...publicState,videos:[],catalog:lessons.map((l,id)=>({id,title:l.title,subtitle:l.subtitle,topic:l.topic,accent:l.accent,description:l.description})),lessonData:s.sessions.filter(x=>!x.done).map(x=>{const l=lessons[x.lesson];return {session:x.id,first:l.first.map(({prompt,options})=>({prompt,options})),again:l.again.map(({prompt,options})=>({prompt,options})),expressions:x.stage>=3?l.expressions:[],sentences:x.stage>=5?l.sentences:[]}})}}
async function load(){const user=await getChatGPTUser();if(!user)throw new Error('AUTH');if(!env.DB)throw new Error('DB');await env.DB.prepare('INSERT OR IGNORE INTO learners (id,data,revision) VALUES (?, ?, 0)').bind(user.userId,JSON.stringify(freshState())).run();const row=await env.DB.prepare('SELECT data,revision FROM learners WHERE id=?').bind(user.userId).first<{data:string;revision:number}>();return {id:user.userId,state:JSON.parse(row!.data) as State,revision:row!.revision,db:env.DB}}
function failure(e:unknown){const message=e instanceof Error?e.message:'Could not save. Try again.';return Response.json({error:message==='AUTH'?'Sign in to save your learning history.':message},{status:message==='AUTH'?401:message==='CONFLICT'?409:400})}
export async function GET(){try{const {state}=await load();return Response.json(view(state),{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&new URL(req.url).origin!==req.headers.get('origin'))return new Response('Forbidden',{status:403});const p=input.parse(await req.json());const {id,state:s,revision,db}=await load();const today=localDate(s.profile.timezone);let session=s.sessions.find(x=>x.id===p.session);const current=()=>{if(!session||session.done)throw new Error('Select an active lesson.');return session};
if(p.action==='profile'){if(!p.profile)throw new Error('Enter your profile information.');localDate(p.profile.timezone);s.profile=p.profile}
if(p.action==='start'){session=s.sessions.find(x=>!x.done);if(!session){if(s.sessions.some(x=>x.date===today&&x.done))throw new Error('You completed today’s lesson. Review your expressions.');const chosen=s.assigned[today]??(s.sessions.length%lessons.length);s.assigned[today]=chosen;session={id:crypto.randomUUID(),date:today,lesson:chosen,stage:0,done:false,seconds:0,lastBeat:Date.now(),skipped:[],attempts:{}};s.sessions.push(session)}}
if(p.action==='swap'){if(s.sessions.some(x=>!x.done))throw new Error('Finish your active lesson first.');s.assigned[today]=((s.assigned[today]??s.sessions.length%lessons.length)+1)%lessons.length}
if(p.action==='attempt'){const x=current(),l=lessons[x.lesson];const key=p.key??'';let target='';if(x.stage===2&&/^d[0-5]$/.test(key))target=l.sentences[Number(key[1])];else if((x.stage===1&&/^f[0-1]$/.test(key))||(x.stage===4&&/^r[0-1]$/.test(key))){target=String((x.stage===1?l.first:l.again)[Number(key[1])].answer)}else throw new Error('This question is not available at the current step.');if(!p.answer?.trim())throw new Error('Enter an answer.');if(!x.attempts[key])x.attempts[key]={answer:p.answer,score:key[0]==='d'?score(p.answer,target):Number(p.answer===target)*100,target,captions:!!p.captions}}
if(p.action==='advance'){const x=current();const required=x.stage===1?['f0','f1']:x.stage===2?['d0','d1','d2','d3','d4','d5']:x.stage===4?['r0','r1']:[];if(!p.skip&&required.some(k=>!x.attempts[k]))throw new Error('Complete the questions or choose Skip Step.');if(p.skip)x.skipped.push(x.stage);if(x.stage===6)x.done=true;else x.stage++;x.lastBeat=Date.now()}
if(p.action==='beat'){const x=current(),now=Date.now(),delta=(now-x.lastBeat)/1000;x.seconds+=Math.max(0,Math.min(15,delta));x.lastBeat=now}
if(p.action==='saveExpression'){const x=current();if(x.stage<3)throw new Error('Save this during the expression practice step.');const e=lessons[x.lesson].expressions[p.index??-1];if(!e)throw new Error('Could not find the expression.');const eid=`${x.lesson}-${p.index}`;if(!s.expressions.some(e=>e.id===eid))s.expressions.push({...e,id:eid,due:nextDate(today,1),interval:1,results:[]})}
if(p.action==='review'){const e=s.expressions.find(e=>e.id===p.key);if(!e||e.due>today)throw new Error('This expression is not due for review today.');e.interval=nextInterval(e.interval,!!p.success);e.results.push(!!p.success);e.due=nextDate(today,e.interval)}
if(p.action==='deleteExpression')s.expressions=s.expressions.filter(e=>e.id!==p.key);
if(p.action==='bookmark'){const i=p.index??-1;if(!lessons[i])throw new Error('Could not find the lesson.');s.saved=s.saved.includes(i)?s.saved.filter(x=>x!==i):[...s.saved,i]}
if(p.action==='candidate'){const u=new URL(p.answer??'');if(!['www.youtube.com','youtube.com','youtu.be'].includes(u.hostname)||u.protocol!=='https:')throw new Error('Enter a YouTube URL that starts with https://.');if(!s.candidates.includes(u.href))s.candidates.push(u.href)}
if(p.action==='reset'){await db.prepare('DELETE FROM learners WHERE id=?').bind(id).run();return Response.json(view(freshState()))}
const result=await db.prepare('UPDATE learners SET data=?, revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(s),id,revision).run();if(!result.meta.changes)throw new Error('CONFLICT');return Response.json(view(s));}catch(e){return failure(e)}}
